- .gitignore
- Dockerfile
- app/app/settings.py
- entrypoint.sh
- requirements.txt
Parts of Daniel's branch, with some other bits. Just reducing it to what is required to test the rest of the pipeline. We can review the remaining bits later.
> Feature: environment

- Dockerfile-dev
- docker-compose.yml
- requirements-dev.txt
Changes in 0e4117e2 broke docker compose.
> Fix compose

- app/app/urls.py
- app/app/views.py
- app/static/css/styles.css
- app/templates/400.html
- app/templates/403.html
- app/templates/404.html
- app/templates/500.html
- app/templates/base_error.html
Add custom error pages, with styling
> Error pages

- .gitignore
- app/app/settings.py
This ensures that all uploads (e.g. documents and logos) are separate from code, regardless of `upload_to` attributes on FileFields. This also allows a single volume to be mounted for all uploads that won't also contain other project files.
> Media settings

- app/app/views.py
In this PR, we ensure the display of institutions is in alphabetical order
> Order institutions in institutions comparison page alphabetically

- app/templates/admin/base_site.html
- app/templates/base.html
In this PR, we ensure that when the logo is clicked, the user is directed to the home page for the admin site, and for the main app
> Make click on logo direct to home page

- app/templates/admin/base_site.html
in this PR, we change admin logo to direct to terminology landing page
> Admin logo to direct to landing page

- app/static/css/styles.css
- app/templates/base.html
In this PR, we fix footer to the bottom of the page
> Fix footer to bottom of web page

- app/app/urls.py
- app/app/views.py
- app/templates/app/search.html
- app/templates/base.html
Add search page template, view, url, and styling
> Add search page

- app/app/views.py
- app/general/admin.py
- app/templates/base.html
In this PR we change return of context current page from view to single variable, to fix aria-current page in template
> Aria-current page for active pages

- README.md
- app/app/settings.py
- app/general/admin.py
- app/general/migrations/0004_historicaldocumentfile_historicalinstitution_and_more.py
- app/general/models.py
- app/general/tests/test_document_file.py
- app/general/tests/tests_institution.py
- app/general/tests/tests_language.py
- app/general/tests/tests_projects.py
- app/general/tests/tests_subject.py
- app/users/admin.py
- app/users/migrations/0003_historicalcustomuser.py
- app/users/models.py
- requirements.txt
Add the following models to simple history
- Project
- Institution
- Language
- Subject
- DocumentFile
- Users
Updated tests
Added new Migrations
Cleaned up admin code while updating
> added django-simple-history to project

- app/app/settings.py
- app/app/views.py
- app/general/tests/test_views_institution.py
- app/templates/app/institutions.html
In this PR, we change the institution view to return context with project count, and display dynamic project count in template
> Add dynamic project count to institutions

- app/static/css/admin.css
changed colour of breadcrumbs and side bar table active headers
> changed colour of breadcrumbs

- app/static/css/admin.css
- app/static/css/dark_mode_override.css
in this PR we change some colours to assist with better lighthouse score
> Accessibility colour changes

- app/templates/app/home.html
> Feature: front page copy

- app/static/css/styles.css
- app/templates/app/institutions.html
In this PR we change styling to accommodate different sized logos
> Alter styling for logos

- app/app/urls.py
- app/app/views.py
- app/general/tests/test_views.py
In this PR, we Fix error pages views so that they are displayed, and add unit test
> Fix error pages views

- Dockerfile
- Dockerfile-dev
- README.md
- app/general/admin.py
- app/general/tests/test_document_admin_file.py
- requirements.txt
- updated admin test
- updated docker files with libmagic1
- updated Readme file
> added magic to check mime_type

- app/app/urls.py
- app/app/views.py
- app/static/css/styles.css
- app/templates/base.html
add languague toggle to base template, add 118n settings to url, add styling for toggle
> Add language toggle

- .gitignore
- Makefile
- README.md
- app/general/management/commands/dev_pdf_mass_upload.py
- app/general/service/extract_text.py
- app/general/tests/test_dev_mass_upload.py
- app/general/tests/test_extract_text_service.py
- docker-compose.yml
- requirements-dev.txt
- requirements-test.txt
- added faker package
- updated readme file
- added new tests
> added mass pdf upload command for testing

- app/app/urls.py
- app/app/views.py
- app/general/tests/test_projects.py
- app/static/css/styles.css
- app/templates/app/projects.html
- app/templates/base.html
Add projects list view, template, url, and styling
> Add projects list page:

- app/general/admin.py
- app/general/models.py
Change document files to documents, and document type to document category
> Change of Document Files

- app/fixtures/institution.json
- app/fixtures/language.json
- app/fixtures/subjects.json
E.g. incorrect language codes, fake e-mail addresses, missing institution, etc.
> fix fixtures

- app/app/urls.py
- app/app/views.py
- app/general/tests/test_project_detail.py
- app/static/css/styles.css
- app/templates/app/project_detail.html
- app/templates/app/projects.html
Add individual project page, with styling and view
> individual projects page

- app/app/views.py
- app/static/css/styles.css
- app/templates/app/documents.html
- app/templates/app/projects.html
- app/templates/base.html
Add template, view, and responsive  styling to document list page
> Create document list page

- app/templates/app/document_detail.html
- app/templates/app/project_detail.html
remove language and subjects links from project_detail and document_detail page respectively
> remove language and subjects links

- app/templates/app/document_detail.html
remove download button if there is no document uploaded
> remove download if no document

- app/app/urls.py
- app/app/views.py
- app/static/css/styles.css
- app/templates/app/contact.html
- app/templates/app/legal_notices.html
- app/templates/base.html
Add about and legal notices templates, urls, views, and styling
> Add about and legal notices pages

- app/app/views.py
- app/general/tests/test_documents.py
- app/templates/app/_subj_lang_institution_filter.html
- app/templates/app/documents.html
- app/templates/app/projects.html
Introduced in 35495e7dc04. The reset link was also hardcoded for the documents view.
> Bug: filter documents by language

- .github/workflows/develop.yml
- .github/workflows/production.yml
- .github/workflows/testing.yml
Fixes #142. That issue has more info on why this is a good thing to do :slightly_smiling_face:
> chore(ci): set GitHub token permissions to read-only for all workflows

- .github/workflows/testing.yml
This will help us catch the mistake I made in #151 in an automated way in the future
> ci: check no migration needed

- app/general/filters.py
- app/general/tests/test_view_search.py
> tweak: only show actionable subjects for search filters

- app/templates/app/home.html
- Adjust the text in the home page to make it relate more to the search box
- Add a horizontal line between the searching & browsing sections to try and differentiate them
- Add `aria-label` attr to the `input`
> Small tweaks to homepage

- app/templates/app/about.html
- app/templates/app/document_detail.html
- app/templates/app/documents.html
- app/templates/app/home.html
- app/templates/app/institution_detail.html
- app/templates/app/institutions.html
- app/templates/app/languages.html
- app/templates/app/legal_notices.html
- app/templates/app/project_detail.html
- app/templates/app/projects.html
- app/templates/app/search.html
- app/templates/app/subjects.html
A tiny bugfix, and some cleanups.
> Tiny front-end fixes

- .github/workflows/testing.yml
Incorrect name introduced in ce0bdf4fe7f620.
CC: @Restioson
> Correct env variable ` JS_ENABLE`

- app/general/tests/test_frontend.py
- app/templates/app/js/page-status.js
- app/templates/base.html
Multiple issues arose when using the browser history. Solved with a mixture of HTMX update and moving JS includes around, with a lot of associated refactorings, etc.
> Bug: JS issues

- app/templates/app/_documents.html
- app/templates/app/_projects.html
- app/templates/app/css/local.css
- app/templates/app/languages.html
- app/templates/app/subjects.html
The accordions are expanded by default if they have <10 items
> Use <details> element for all documents & projects on subject/language pages
