- app/general/admin.py
I get the linter's point. In a mature project __all__ is maybe not a good idea. I think it is a bit too pedantic in this case (as "__all__ " is documented by the project as the right way to do it), and the function call `fields_for_model()` is equivalent. So the linter just isn't clever enough to complain about the function call as it suffers from exactly the same weak points. See https://docs.astral.sh/ruff/rules/django-all-with-model-form/
> ruff override

- app/app/settings.py
Variable name change for staticfiles storage, to a variable not used  by django
> Change staticfiles storage variable name

- app/static/css/admin.css
- app/static/css/dark_mode_override.css
- app/templates/admin/base_site.html
In this PR, we add a dark mode css file that extends from the django dark mode one, with styling according to SADiLaR colours
> Add dark mode css file, and add to admin template

- app/general/service/extract_text.py
Any error in pypdf crashes the bulk import command instead of just skipping the problematic file. E.g.
```
Traceback (most recent call last):
...
File "/app/general/service/extract_text.py", line 18, in to_text
reader = PdfReader(self.uploaded_file)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pypdf/_reader.py", line 127, in __init__
self.read(stream)
File "/usr/local/lib/python3.12/site-packages/pypdf/_reader.py", line 543, in read
xref_issue_nr = self._get_xref_issues(stream, startxref)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pypdf/_reader.py", line 945, in _get_xref_issues
stream.seek(startxref - 1, 0)  # -1 to check character before
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: negative seek value -1
```
> Bug: handle pypdf errors

- app/app/views.py
- app/static/css/styles.css
- app/templates/app/institution_detail.html
- app/templates/app/institutions.html
- app/templates/app/project_detail.html
- app/templates/app/projects.html
Add changes to styling and template according to new spec, and refactor css
> Add changes to styling and template

- app/accounts/forms.py
- app/accounts/views.py
- app/static/css/styles.css
- app/templates/accounts/login.html
- app/templates/accounts/password_reset_complete.html
- app/templates/accounts/password_reset_confirm.html
- app/templates/accounts/password_reset_done.html
- app/templates/accounts/password_reset_form.html
- app/templates/accounts/register.html
- app/templates/base_error.html
Add user manangement views, templates, and styling
> user management frontend

- app/app/urls.py
- app/app/views.py
- app/general/tests/test_document_detail.py
- app/templates/app/document_detail.html
- app/templates/app/documents.html
Add document detail view, url, and template
> individual document page

- app/app/views.py
- app/general/tests/tests_subject.py
- app/templates/app/languages.html
- app/templates/app/subjects.html
- app/templates/base.html
Add view, template, unit test, and styling for subjects page
> Subjects list page

- app/app/settings.py
- app/general/middleware.py
This fixes the problem with a partial page showing on browser restore, or for example with Firefox plugin "Auto Tab Discard" if a tab is restored. It will also be required if "real" caching is implemented.
> Ensure HTML pages vary on HX-Request

- app/templates/app/project_detail.html
Before this change, the screen-reader would simply read "End Date:" and trail off. Now, it will read "End Date: Ongoing". For sighted users, the text is slightly greyed-out to indicate that the end date is not _really_ there (as the project is ongoing).
> fix(a11y): put 'ongoing' after 'end date'

- .github/workflows/testing.yml
This change prevents duplicate runs from occurring when opening a pull request on GitHub. Before, both the 'push' and 'pull_request' hooks would trigger, meaning that any push to a branch with an open PR would run the CI pipeline twice. By filtering the 'push' hook to 'main' and 'develop', we avoid this.
The tangible benefit of this is
1. we avoid oversubmitting GitHub CI jobs, so if we have more jobs to run in the future (see #132, which will add a new, separate lighthouse job), we get all the results quicker
2. fixes the annoyance of having two failures/successes when it should only really be one
> chore(ci): don't run push & PR on PR branches

- Dockerfile
This is better as app/ will likely change more often than entrypoint.sh. Thus, this change increases the degree to which the container's build layers can be cached
> fix(build): copy entrypoint before app

- .github/workflows/testing.yml
This makes sure we don't accidentally merge commits which should be squashed up or rebased first.
> chore(ci): lint for bang commits (fixup, squash, drop, edit)

- .github/workflows/develop.yml
- .github/workflows/production.yml
- .github/workflows/testing.yml
- Makefile
- README.md
- app/general/tests/test_frontend.py
Fixes include:
- Running tests for specific modules from `make test` (pass `module=...`)
- Added some notes to developers in the README
- Designated all Makefile targets as PHONY
- Added `lint` and `fmt` aliases to Makefile
- Fix import order in `test_frontend.py`
- Actually run the linter in CI
> Assorted dev experience & CI fixes

- .github/workflows/testing.yml
- Makefile
- app/general/tests/files/test_js.html
- app/general/tests/test_frontend.py
By passing the browser type and whether JS is enabled via environment variables, we can run the Selenium front-end tests on all combinations of targeted browsers and JS/no-JS in the CI pipeline. The way it works from the CI perspective is by using a Matrix strategy which is then substituted into an environment variable when calling `manage.py test --tag=selenium`
Fixes #143. However, #145 is not addressed, as this PR doesn't tackle Safari. This is because GitHub Actions MacOS workers don't support  `services`, which  we use to run the postgres database. This can be left for a follow-up PR.
> test: run Selenium tests on more browsers/JS configurations

- app/accounts/admin.py
- app/accounts/models.py
- app/accounts/views.py
- app/app/urls.py
- app/general/filters.py
- app/general/management/commands/import_documents.py
- app/general/templatetags/bs_icons.py
- app/general/tests/test_document_detail.py
- app/general/tests/test_filter.py
- app/general/tests/test_frontend.py
- app/general/tests/test_import_documents.py
- app/general/tests/test_project_detail.py
- app/general/tests/test_view_search.py
- app/general/tests/test_views_institution.py
- app/pyproject.toml
By changing `select` to `extend-select`, we keep the default Ruff lints enabled. Additionally, there are some more lints that we care about that have both been enabled and fixed in this commit.
> Expanded linting

- Makefile
This is just slightly easier to remember & type than `make ruff-fix && make fmt`
> dev: add `fix` Makefile command to call ruff fix and format

- .github/workflows/testing.yml
We have a lot of useless variables and things that don't make sense
> ci: simplify environment variables in CI scripts

- app/app/views.py
- app/general/models.py
- app/general/tests/test_documents.py
- app/general/tests/tests_projects.py
The page is pretty snappy, so I don't think caching will be needed at this time (maybe if it's slow on the test deployment). It is the same number of queries overall (though one of them is a bit heavier, being a join compared to a simple select).
> tweak: only show subjects which have documents or projects associated

- app/templates/app/about.html
> fix: align leftmost contact column text to title

- app/templates/app/_documents.html
- app/templates/app/css/local.css
- app/templates/app/languages.html
- app/templates/app/subjects.html
This hopefully makes rendering and browsing the languages and subjects pages a bit simpler, and refactors a reused bit. We can consider doing the same for projects.
The custom CSS is to work correctly without Bootstrap's JS on browsers that support the [open] selector (should be almost 100% supported now), and to fix a webkit/safari bug (visible with the GNOME browser).
> Avoid long lists of documents

- app/templates/app/css/local.css
`animation` now correctly has a delay of 1s, which was the idea all along. Alpha is added to the static background so that it would not obscure underlying content before the animation starts. This way no indicator is shown if the response arives fast enough. Alpha is increased for the indicator to compensate for any loss of contrast with the white background now gone.
> Fix+tweak styling of htmx-indicator

- app/general/middleware.py
I saw an error for this, but don't have a case to reproduce this. Seems safer this way anyway.
> Conditionally handle header

- .github/workflows/testing.yml
- app/lighthouserc.js
This CI job started failing after a quiet period. Upgrading lhci to 0.15 fixed it, but brought new issues as mentioned in the comment.
> Upgrade lhci to 0.15.x
